user1 = User.create(first_name: "Alex", last_name: "Chao", email: "alex@chao.com", password: "password")
user2 = User.create(first_name: "Alfred", last_name: "Wang", email: "alfred@wang.com", password: "password")
user3 = User.create(first_name: "Hassan", last_name: "Malik", email: "hassan@malik.com", password: "password")
user4 = User.create(first_name: "Andy", last_name: "Chadha", email: "andy@chadha.com", password: "password")

quiz = user1.quizzes.create(title: "First Grade Math", description: "This quiz is suitable for children in first grade. The math is based on Common Core State Standards. This quiz challenges students to see how math can be fun!")

first_question = quiz.questions.new(title: "What is 1 + 1?", difficulty: "easy")
first_question_first_choice = first_question.choices.new(answer: 18)
first_question_second_choice = first_question.choices.new(answer: 7)
first_question_third_choice = first_question.choices.new(answer: 2, correct: true)
first_question_fourth_choice = first_question.choices.new(answer: 10)
first_question.save()

second_question = quiz.questions.new(title: "What is 3 + 3?", difficulty: "easy")
second_question_first_choice = second_question.choices.new(answer: 33)
second_question_second_choice = second_question.choices.new(answer: 1)
second_question_third_choice = second_question.choices.new(answer: 7)
second_question_fourth_choice = second_question.choices.new(answer: 6, correct: true)
second_question.save()

third_question = quiz.questions.new(title: "What is 5 + 5?", difficulty: "easy")
third_question_first_choice = third_question.choices.new(answer: 10, correct: true)
third_question_second_choice = third_question.choices.new(answer: 4)
third_question_third_choice = third_question.choices.new(answer: 9)
third_question_fourth_choice = third_question.choices.new(answer: 1)
third_question.save()

fourth_question = quiz.questions.new(title: "What is 7 + 7?", difficulty: "easy")
fourth_question_first_choice = fourth_question.choices.new(answer: 12)
fourth_question_second_choice = fourth_question.choices.new(answer: 14, correct: true)
fourth_question_third_choice = fourth_question.choices.new(answer: 18)
fourth_question_fourth_choice = fourth_question.choices.new(answer: 77)
fourth_question.save()
